spring.datasource.driver-class-name: org.postgresql.Driver
spring.jpa.show-sql: true
spring.jpa.properties.hibernate.dialect:  org.hibernate.dialect.PostgreSQLDialect

dgs.graphql.extensions.scalars.ids.enabled: true

spring.datasource.url: ${DB_URL:jdbc:postgresql://localhost:5432/paper_scissors_rock_db}
spring.datasource.username: ${DB_USERNAME:test}
spring.datasource.password: ${DB_PASSWORD:test}

application:
  banner: false
